version: "3"

services:
  
  flask:
    build: 
      context: ./docker-manager-flask
      dockerfile: Dockerfile
    image: guojiaxing1995/docker-manager-flask:v1
    container_name: docker-manager-flask
    restart: always
    expose:
      - 5005
    networks:
      - docker-manager
    volumes:
      - ./config/:/docker-manager-flask/app/config/
      
  exec:
    build: 
      context: ./docker-manager-exec
      dockerfile: Dockerfile
    image: guojiaxing1995/docker-manager-exec:v1
    container_name: docker-manager-exec
    restart: always
    expose:
      - 5006
    networks:
      - docker-manager
    volumes:
      - ./config/:/docker-manager-exec/config/
           
  vue:
    build: 
      context: ./docker-manager-vue
      dockerfile: Dockerfile
    image: guojiaxing1995/docker-manager-vue:v1
    container_name: docker-manager-vue
    restart: always
    ports:
      - 8085:80
    links:
      - flask
    networks:
      - docker-manager
  
networks:
  docker-manager:
    driver: bridge
